[package]
name = "custom_customs"
version = "0.1.0"
authors = ["dangeli <dageli@us.ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
